name = "AdventOfCode2024"
uuid = "111b8d13-a469-4adf-8804-f5a82a319848"
authors = ["Felix Augustsson <git.fexilus@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
BenchmarkTools = "1.5.0"
DataStructures = "0.18.20"
Test = "1.11.0"
