name = "AdventOfCode2024"
uuid = "111b8d13-a469-4adf-8804-f5a82a319848"
authors = ["Felix Augustsson <git.fexilus@gmail.com>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Test = "1.11.0"
